# Generated by Django 5.1.2 on 2024-10-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('max_duration', models.TimeField()),
                ('description', models.TextField()),
                ('user', models.ManyToManyField(to='tgusers.tguser')),
            ],
        ),
    ]
