# Generated by Django 5.1.2 on 2024-10-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='max_duration',
            field=models.DurationField(),
        ),
    ]
