# Generated by Django 5.1.2 on 2024-10-13 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_stand'),
        ('stands', '0003_stand_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stand', to='events.event'),
        ),
    ]
